clc
open('../figs/FigureA6_recvar_SNR.fig')
ax2 = axes('Position',get(gca,'Position'),...
    'XAxisLocation','top',...
    'YAxisLocation','right',...
    'Color','none',...
    'XColor','k','YColor','k')%,...
%     'YTick',0:10:80,...
%     'YTickLabel',1:8);
% 
% l2 = line(x2,y2,'Color','k','Parent',ax2);