clc
open('../figs/FigureA6_recvar_SNR.fig')

h=get(gcf,'Children');

h1=get(h(2),'Children');

x1=get(h1(1),'XData'); y1=get(h1(1),'YData');

x2=get(h1(2),'XData'); y2=get(h1(2),'YData');

x3=get(h1(3),'XData'); y3=get(h1(3),'YData');


% h=get(gcf,?Children?);
% 
% h1=get(h(2),?Children?);
% 
% x1=get(h1(1),?XData?); y1=get(h1(1),?YData?);
% 
% x2=get(h1(2),?XData?); y2=get(h1(2),?YData?);
% 
% x3=get(h1(3),?XData?); y3=get(h1(3),?YData?);

%%
X1=x1;
YMatrix1=[y1; y2; y3];
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 04-Aug-2009 09:41:49

% Create figure
figure1 = figure('XVisual',...
    '0x24 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'FontSize',12,'FontName','Arial');
box('on');
hold('all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'MarkerSize',16,'Marker','.',...
    'LineWidth',2,...
    'Color',[0 0 0]);
set(plot1(1),'DisplayName','66Hz');
set(plot1(2),'LineStyle','--','DisplayName','33Hz');
set(plot1(3),'LineStyle',':','DisplayName','15Hz');

% Create xlabel
xlabel('Photon budget, Kph/neuron/frame','FontSize',12,'FontName','Arial');

% Create ylabel
ylabel('Recovered variance','FontSize',12,'FontName','Arial');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','NorthWest');


%%
ax2 = axes('Position',get(gca,'Position'),...
    'XAxisLocation','top',...
    'YAxisLocation','right',...
    'Color','none',...
    'XColor','r','YColor','k',...
    'XTickLabel',1:8,...
    'YTickLabel',[]);
%     'XTick',0:10:80,...
% 
% l2 = line(x2,y2,'Color','k','Parent',ax2);